### PR TITLE
feat(datacatalog): add taxonomy & policy tags resources

### PR DESCRIPTION
**Pull request by nilan3**
### Description of your changes

Add resources for the following terraform resources:

- google_data_catalog_taxonomy
- google_data_catalog_policy_tag

I have:

- [X] Read and followed Crossplane's [contribution process].
- [X] Run `make reviewable` to ensure this PR is ready for review.
- [X] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested
Running Uptest locally against a personal sandbox GCP project

`UPTEST_EXAMPLE_LIST="examples/datacatalog/v1beta1/policytag.yaml"`

```bash
--- PASS: kuttl (50.28s)
    --- PASS: kuttl/harness (0.00s)
        --- PASS: kuttl/harness/case (49.02s)
PASS
10:45:53 [ OK ] running automated tests
```
image
image

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by nilan3** [comment]
/test-examples="examples/datacatalog/v1beta1/policytag.yaml"

**Comment by nilan3** [comment]
can I please request to be a contributor for this repo?

**Comment by jeanduplessis** [comment]
> can I please request to be a contributor for this repo?

Upon successful merging of your first PR you will automatically become a contributor.

**Comment by jeanduplessis** [comment]
/test-examples="examples/datacatalog/v1beta1/policytag.yaml"

**Comment by nilan3** [comment]
> /test-examples="examples/datacatalog/v1beta1/policytag.yaml"

could you re run this test pls? I've just added a validation rule to the CRD

**Comment by turkenf** [comment]
/test-examples="examples/datacatalog/v1beta1/policytag.yaml"

**Comment by turkenf** [comment]
Could you please remove the API files of the resources you did not add?

**Review by nilan3 — COMMENTED** [review]
@turkenf thanks for the comment, those files are cleaned up

**Comment by nilan3** [comment]
@turkenf thanks for the comment, those files are cleaned up

**Comment by jeanduplessis** [comment]
/test-examples="examples/datacatalog/v1beta1/policytag.yaml"

**Comment by jeanduplessis** [comment]
/test-examples="examples/datacatalog/v1beta1/taxonomy.yaml"

**Comment by nilan2** [comment]
/test-examples="examples/datacatalog/v1beta1/taxonomy.yaml"

**Comment by nilan3** [comment]
/test-examples="examples/datacatalog/v1beta1/taxonomy.yaml"

**Comment by nilan3** [comment]
> /test-examples="examples/datacatalog/v1beta1/taxonomy.yaml"

@jeanduplessis could you help with running this test again. I've just done a complete clean up

**Comment by jeanduplessis** [comment]
/test-examples="examples/datacatalog/v1beta1/taxonomy.yaml"

**Comment by nilan3** [comment]
> /test-examples="examples/datacatalog/v1beta1/taxonomy.yaml"

@jeanduplessis do you know why the CI checks could be failing? It's failing on 'Vendor dependencies' stage

**Comment by turkenf** [comment]
> @jeanduplessis do you know why the CI checks could be failing? It's failing on 'Vendor dependencies' stage

@nilan3, could you please run `go mod tidy` then run `make generate` and push the changes?

Screenshot 2024-10-30 at 14 16 27

**Comment by nilan3** [comment]
@turkenf it looks like `make crddiff` is failing with the following error:

```bash
09:59:40 [ .. ] installing uptest /workspaces/provider-upjet-gcp-1/.cache/tools/linux_x86_64/uptest-v0.11.1
curl: (22) The requested URL returned error: 404
09:59:41 [FAIL]
make: *** [build/makelib/k8s_tools.mk:204: /workspaces/provider-upjet-gcp-1/.cache/tools/linux_x86_64/uptest-v0.11.1] Error 1
```

Also I've had to modify the CRD conditions after running `make generate`
image

**Comment by turkenf** [comment]
Hi @nilan3 , thank you for your efforts.

The issue we got in the report-breaking changes pipeline seems meaningless/temporary; Similarly, [here](https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/11562279687/job/32183103346?pr=641) is passed. If you have time, can you reset your branch to main, add only the external name configurations of the resources you will add, run make generate, then add the examples and push with the new commit(s). This can help us get rid of temporary/meaningless errors.

Also, please do not make any manual changes to the generated files and CRDs and please sign the DCO.

Thanks in advance!

**Pull request closed without merging**
