### PR TITLE
Update Upjet to v1.4.1-0.20241007154751-5cdf36996e4a

### PR DESCRIPTION
**Pull request by rickard-von-essen**
### Description of your changes

This updated upjet to `v1.4.1-0.20241007154751-5cdf36996e4a` which includes https://github.com/crossplane/upjet/pull/441

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] ~Added `backport release-x.y` labels to auto-backport this PR if necessary.~

### How has this code been tested

This has been partly tested in #624.

And via uptest:

- `examples/cloudplatform/v1beta1/serviceaccount.yaml` => https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/11466746111
- `examples/storage/v1beta2/bucket.yaml` => https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/11466747605
- `examples/compute/v1beta2/instancetemplate.yaml` => https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/11467922255
- `examples/binaryauthorization/v1beta2/policy.yaml` => https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/11467924811

### CODE REVIEW

**Comment by turkenf** [comment]
**Checking the newly added reference fields from the terraform registry**

- [x] `apis/beyondcorp/v1beta2/zz_appconnection_types.go`: `connectors`
- [ ] `apis/binaryauthorization/v1beta2/zz_policy_types.go` : `cluster_admission_rules.require_attestations_by`, check external name configuration for extractor
- [x] `apis/certificatemanager/v1beta1/zz_certificatemapentry_types.go` : `certificates`
- [x] `apis/certificatemanager/v1beta2/zz_certificate_types.go` : `managed.dns_authorizations`, `managed.domains`
- [x] `apis/cloudrun/v1beta2/zz_v2job_types.go` : `...cloud_sql_instance.instances`
- [x] `apis/cloudrun/v1beta2/zz_v2service_types.go` : `...cloud_sql_instance.instances`
- [x] `apis/compute/v1beta1/zz_instancegroup_types.go` : `instances`
- [x] `apis/compute/v1beta1/zz_interconnectattachment_types.go` : `ipsec_internal_addresses`
- [x] `apis/compute/v1beta2/zz_instancetemplate_types.go` : `disk.resource_policies`
- [x] `apis/compute/v1beta2/zz_routernat_types.go` : `action.source_nat_active_ips`, `nat_ips`
- [x] `apis/osconfig/v1beta2/zz_patchdeployment_types.go` : `instance_filter.instances`

**Comment by turkenf** [comment]
/test-examples="examples/cloudplatform/v1beta1/serviceaccount.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/binaryauthorization/v1beta2/policy.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/v1beta2/instancetemplate.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/v1beta2/instancetemplate.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/binaryauthorization/v1beta2/policy.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @rickard-von-essen for the upjet change (this also helped adding some new reference fields🎉) and consuming it here. Also thanks @turkenf for reviewing it. LGTM!

**Review by turkenf — APPROVED** [review]

**Pull request merged**
