### PR TITLE
bump go version to 1.23

### PR DESCRIPTION
**Pull request by erhancagirici**
### Description of your changes

bump go version to 1.23

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested
CI

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by turkenf** [comment]
/test-examples="examples/compute/v1beta1/healthcheck.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/v1beta1/subnetwork.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/container/v1beta2/cluster.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @erhancagirici LGTM!

**Pull request merged**
