### PR TITLE
Introduce MR metrics

### PR DESCRIPTION
**Pull request by mergenci**
### Description of your changes

Consume https://github.com/crossplane/crossplane-runtime/pull/683 and https://github.com/crossplane/upjet/pull/390.

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

I haven't tested yet, because I don't have my GCP ProviderConfig set up. Testing steps can be found at https://github.com/crossplane-contrib/provider-upjet-aws/pull/1281.

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by mergenci** [comment]
/test-examples="examples/cloudplatform/serviceaccount.yaml"

**Comment by mergenci** [comment]
/test-examples="examples/cloudplatform/serviceaccount.yaml"

**Review by ulucinar — APPROVED** [review]
Thanks @mergenci, lgtm.

**Comment by ulucinar** [comment]
Hi @turkenf,
Let's mention about the `Ready` and `Sync` column swap in `kubectl get` output in the release notes as we did before for the other providers.

**Pull request merged**
