### PR TITLE
Update Terraform Provider to v5.38.0

### LINKED ISSUE #577: Request for `labels` field `google_compute_global_address` resource
### What resource do you need?

Terraform Resource Name: [`google_compute_global_address`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_global_address)
Field name: [`labels`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_global_address#labels)

### What is your use case?

The field was [previously only available in the Beta Terraform Provider](https://registry.terraform.io/providers/hashicorp/google/5.37.0/docs/resources/compute_global_address#labels), `v5.38.0` moved it to GA.

### PR DESCRIPTION
**Pull request by mauricewittek**
### Description of your changes

Fixes #577

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by mauricewittek** [comment]
Hey @turkenf,

thanks for the detailed explanation, I hope I got everything right this time.

**Comment by turkenf** [comment]
> thanks for the detailed explanation, I hope I got everything right this time.

@mauricewittek, I haven't checked it in detail, but the changes you made seem proper. But we may have to wait for this PR for a while due to the problem mentioned in this [comment](https://github.com/crossplane-contrib/provider-upjet-gcp/issues/561#issuecomment-2235980884), which we should fix.

We also need to investigate why the `v1beta2` versions of the `Table.bigtable` and `Dataset.healthcare` resources, which we noticed in this PR, were created. We may need to remove these versions if necessary.

I will keep you informed, thank you 🙏

**Comment by turkenf** [comment]
Hi @mauricewittek, 

After [this fix](https://github.com/crossplane-contrib/provider-upjet-gcp/pull/585), we should no longer generate `v1beta2` versions for the resources I mentioned above. Could you please reset your branch to main, make changes in `Makefile` and `go.mod`, and run `make generate` again?

**Comment by mauricewittek** [comment]
@turkenf I messed this up somehow. :see_no_evil: 

I opened up a new PR here, hope this is ok: https://github.com/crossplane-contrib/provider-upjet-gcp/pull/593

**Pull request closed without merging**
