### PR TITLE
Update Terraform Provider to v5.39.0

### LINKED ISSUE #577: Request for `labels` field `google_compute_global_address` resource
### What resource do you need?

Terraform Resource Name: [`google_compute_global_address`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_global_address)
Field name: [`labels`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_global_address#labels)

### What is your use case?

The field was [previously only available in the Beta Terraform Provider](https://registry.terraform.io/providers/hashicorp/google/5.37.0/docs/resources/compute_global_address#labels), `v5.38.0` moved it to GA.

### PR DESCRIPTION
**Pull request by mauricewittek**
### Description of your changes

This PR upgrades the Terraform provider version to `v5.39.0`

Fixes #577
Fixes https://github.com/crossplane-contrib/provider-upjet-gcp/issues/561

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

**Manually**
- `examples/alloydb/v1beta1/cluster.yaml` and Uptest:https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/10266597573
```
NAME                                          SYNCED   READY   EXTERNAL-NAME   AGE
cluster.alloydb.gcp.upbound.io/alloydb-test   True     True    alloydb-test    7m7s
```
- `examples/bigquery/v1beta1/connection.yaml` => Uptest fails due to an update loop on the dependent [DatabaseInstance](https://github.com/crossplane-contrib/provider-upjet-gcp/issues/598) resource, the Connection resource tested successfully:
```
NAME                                                    SYNCED   READY   EXTERNAL-NAME
  AGE
connection.bigquery.gcp.upbound.io/connection-fttest5   True     True    projects/official-provider-testing/locations/US/connections/6b8b0517-bffd-42b7-9811-2a415cb97c71
  41m
```
- `examples/bigquery/v1beta1/table.yaml` => Uptest failed due to id change
```
NAME                                    SYNCED   READY   EXTERNAL-NAME   AGE
table.bigquery.gcp.upbound.io/default   True     True    default         32m
```

**Uptest**

- `examples/artifact/v1beta1/registryrepository.yaml` => https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/10251167949
- `examples/bigquery/v1beta1/dataset.yaml` => https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/10251169622
- `examples/bigtable/v1beta1/appprofile.yaml` => https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/10254413056
- `examples/bigtable/v1beta1/instance.yaml` => https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/10251172457
- `examples/compute/v1beta1/backendservice.yaml` => https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/10254428661
- `examples/compute/v1beta1/firewall.yaml` => https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/10253797284
- `examples/compute/v1beta1/instance.yaml` => https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/10254442870
- `examples/compute/v1beta2/router.yaml` => https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/10253799068
- `examples/container/v1beta1/nodepool.yaml` => https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/10255240004
- `examples/container/v1beta2/cluster.yaml` => https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/10253802521
- `examples/datafusion/v1beta1/instance.yaml` => https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/10255070133
- `examples/dns/v1beta2/policy.yaml` => https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/10253808520
- `examples/gke/v1beta1/backupbackupplan.yaml` => https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/10254515114
- `examples/networkconnectivity/v1beta1/hub.yaml` => https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/10251165472
- `examples/pubsub/v1beta1/topic.yaml` => https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/10254532142
- `examples/spanner/v1beta2/database.yaml` => https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/10253810349
- `examples/sql/v1beta1/instance.yaml` => https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/10254010444
- `examples/storage/v1beta1/bucket.yaml` => https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/10254537156
- `examples/storage/v1beta2/bucket.yaml` => https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/10253812629
- `examples/compute/v1beta2/instancefromtemplate.yaml` => https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/10256057021
- `examples/cloudplatform/v1beta2/serviceaccountiammember.yaml` => https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/10256058380

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by turkenf** [comment]
Many thanks for your effort, @mauricewittek; your changes look fine. Since we need to progress faster in this PR, we will take over the PR to support the newly added fields in older versions and to update the provider to the latest version. 

We welcome you to follow this PR and let us know if you have any suggestions 🙏

**Comment by turkenf** [comment]
/test-examples="examples/networkconnectivity/v1beta1/hub.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/alloydb/v1beta1/cluster.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/artifact/v1beta1/registryrepository.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/v1beta1/connection.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/v1beta1/dataset.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/v1beta1/table.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigtable/v1beta1/instance.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/v1beta1/dataset.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/v1beta1/dataset.yaml"

**Comment by mergenci** [comment]
/test-examples="examples/bigquery/v1beta1/dataset.yaml"

**Comment by mergenci** [comment]
/test-examples="examples/alloydb/v1beta1/cluster.yaml"

**Comment by mergenci** [comment]
/test-examples="examples/bigquery/v1beta1/table.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/networkconnectivity/v1beta1/hub.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/alloydb/v1beta1/cluster.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/artifact/v1beta1/registryrepository.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/v1beta1/connection.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/v1beta1/dataset.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/v1beta1/table.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigtable/v1beta1/instance.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/alloydb/v1beta1/cluster.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/v1beta1/firewall.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/v1beta2/router.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/container/v1beta2/cluster.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/dns/v1beta2/policy.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/storage/v1beta2/bucket.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/alloydb/v1beta1/cluster.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/sql/v1beta1/databaseinstance.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/sql/v1beta1/instance.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigtable/v1beta1/appprofile.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/v1beta1/backendservice.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/v1beta1/instance.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/datafusion/v1beta1/instance.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/gke/v1beta1/backupbackupplan.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/pubsub/v1beta1/topic.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/storage/v1beta1/bucket.yaml "

**Comment by turkenf** [comment]
/test-examples="examples/container/v1beta1/nodepool.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/v1beta2/instancefromtemplate.yaml"

**Review by mergenci — APPROVED** [review]
Thanks for joining the roller coaster ride @turkenf 😅 Special thanks to @mauricewittek for the ticket 🙂

**Pull request merged**
