### PR TITLE
Only apply CRD API conversions for converting between singleton list and embedded objects APIs

### PR DESCRIPTION
**Pull request by turkenf**
### Description of your changes

Only apply the CRD API conversions for converting between singleton list & embedded object APIs for the already existing resources with the generated singleton list CRD APIs.

When we try to add a new Terraform resource with a singleton list in its schema, currently, we need to do a manual configuration such as the following:
```go
p.AddResourceConfigurator("azurerm_pim_active_role_assignment", func(r *config.Resource) {
		r.PreviousVersions = nil
		r.Version = "v1beta1"
		r.Conversions = nil
		r.TerraformConversions = []config.TerraformConversion{
			config.NewTFSingletonConversion(),
		}
	})
```
, so that the API converters registered are removed and versioning starts with `v1beta1` instead of `v1beta2` (for such new resources, the `v1beta1` version does not already exist).

This PR records the names of resources with previous CRD APIs containing (now converted) singleton lists so that the API converters are only registered for them.
This makes adding new resources with singleton lists in their Terraform schemas easier by removing the need to do a manual configuration like shown above.

The newly introduced list should mostly be immutable (it records a set of existing resources with a specific condition at a point in time). Bugs may result in exceptions where we may need to update this list. In other words, new resources should normally be never added to this list, doing so will result in an invalid configuration.

Counterpart PR: https://github.com/crossplane-contrib/provider-upjet-azure/pull/767

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] ~Added `backport release-x.y` labels to auto-backport this PR if necessary.~

### How has this code been tested

Via uptest:
- `examples/cloudplatform/v1beta2/serviceaccountiammember.yaml` https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/10043419025
- `examples/compute/v1beta2/instancefromtemplate.yaml` https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/10043417650
- `examples/cloudplatform/v1beta1/serviceaccount.yaml` https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/10043535773

and tested by generating `google_apigee_addons_config` trying to add with https://github.com/crossplane-contrib/provider-upjet-gcp/pull/581
```
> git status
On branch sl-config
	apis/apigee/v1beta1/zz_addonsconfig_terraformed.go
	apis/apigee/v1beta1/zz_addonsconfig_types.go
	examples-generated/apigee/v1beta1/addonsconfig.yaml
	internal/controller/apigee/addonsconfig/
	package/crds/apigee.gcp.upbound.io_addonsconfigs.yaml
``` 

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by turkenf** [comment]
/test-examples="examples/compute/v1beta2/instancefromtemplate.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/cloudplatform/v1beta2/serviceaccountiammember.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/cloudplatform/v1beta1/serviceaccount.yaml"

**Review by mergenci — APPROVED** [review]
Thanks @turkenf 🙏 LGTM.

**Pull request merged**
